# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "fedora/34-cloud-base"
  
  config.vm.define "fedora" do |fedora|
    fedora.vm.hostname = "fedora"
    fedora.vm.provider "libvirt" do |lv|
      lv.memory = 1024
    end
  end

end
