Vagrant.configure("2") do |config|

    config.vm.define "ubuntu" do |ubuntu|
      ubuntu.vm.box = "generic/ubuntu2004"
      ubuntu.vm.hostname = "ubuntu"
      ubuntu.vm.synced_folder "../../../provisioning/ansible/apt", "/vagrant", type: "rsync"
      ubuntu.vm.provision "ansible_local" do |ansible|
        #ansible.install_mode = "pip"
        ansible.become = true
        ansible.playbook = "/vagrant/cockpit.yml"
      end
    end

end