Vagrant.configure("2") do |config|

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu2004"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.provision "shell", path: "../scripts/apt/dist-upgrade.sh"
  end

  config.vm.define "ubuntu-desktop" do |ubuntud|
    ubuntud.vm.box = "generic/ubuntu2004"
    ubuntud.vm.hostname = "ubuntu-desktop"
    ubuntud.vm.provision "shell", path: "../scripts/apt/apt-mirror-updater.sh"
    ubuntud.vm.provision "shell", path: "../scripts/apt/dist-upgrade.sh"
    ubuntud.vm.provision "shell", path: "../scripts/apt/ubuntu-desktop.sh"
    ubuntud.vm.provision "shell", inline: <<-SHELL
      reboot
    SHELL
  end

  config.vm.define "docker" do |docker|
    docker.vm.box = "generic/ubuntu2004"
    docker.vm.hostname = "docker"
    docker.vm.provision "shell", path: "../scripts/apt/dist-upgrade.sh"
    docker.vm.provision "shell", path: "../scripts/apt/docker.sh"
  end

  config.vm.define "tuya-convert" do |tuya|
    tuya.vm.box = "generic/ubuntu2004"
    tuya.vm.hostname = "tuya-convert"
    #tuya.vm.provider :libvirt do |libvirt|
    #  libvirt.redirdev :type => "spicevmc"
    #end
    tuya.vm.provision "shell", path: "../scripts/apt/dist-upgrade.sh"
    tuya.vm.provision "shell", path: "../scripts/apt/tuya-convert.sh"
  end

end
