Vagrant.configure("2") do |config|

  # ubuntu
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "generic/ubuntu2004"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.provision "shell", path: "../scripts/apt/dist-upgrade.sh"
  end

  # ubuntu-desktop
  config.vm.define "ubuntu-desktop" do |ubuntudesk|
    ubuntudesk.vm.box = "generic/ubuntu2004"
    ubuntudesk.vm.hostname = "ubuntu-desktop"
    ubuntudesk.vm.provision "shell", path: "../scripts/apt/apt-mirror-updater.sh"
    ubuntudesk.vm.provision "shell", path: "../scripts/apt/dist-upgrade.sh"
    ubuntudesk.vm.provision "shell", path: "../scripts/apt/ubuntu-desktop.sh"
    ubuntudesk.vm.provision "shell", inline: <<-SHELL
      reboot
    SHELL
  end

  # docker
  config.vm.define "docker" do |docker|
    docker.vm.box = "generic/ubuntu2004"
    docker.vm.hostname = "docker"
    docker.vm.provision :docker
    docker.vm.provision :docker_compose
  end

  # tuya-convert
  config.vm.define "tuya-convert" do |tuya|
    tuya.vm.box = "generic/ubuntu2004"
    tuya.vm.hostname = "tuya-convert"
    #tuya.vm.provider :libvirt do |libvirt|
    #  libvirt.redirdev :type => "spicevmc"
    #end
    tuya.vm.provision "shell", path: "../scripts/apt/dist-upgrade.sh"
    tuya.vm.provision "shell", path: "../scripts/apt/tuya-convert.sh"
  end

  # OpenWRT - DD-WRT - Tomato
  ## Ubuntu VMs for LAN 192.168.100.0/24
  (0..2).each do |i|
    config.vm.define "ubuntu-10#{i}" do |ubuntu100|
      ubuntu100.vm.box = "generic/ubuntu2004"
      ubuntu100.vm.hostname = "ubuntu-10#{i}"
      ubuntu100.vm.network :public_network,
        :dev => "legion"#,
        #:mode => "bridge",
        #:type => "bridge"
      ubuntu100.vm.provider :libvirt do |libvirt|
        libvirt.memory = 384
      end
    end
  end

  ## Ubuntu VMs for LAN 192.168.200.0/25
  (0..2).each do |i|
    config.vm.define "ubuntu-20#{i}" do |ubuntu200|
      ubuntu200.vm.box = "generic/ubuntu2004"
      ubuntu200.vm.hostname = "ubuntu-20#{i}"
      ubuntu200.vm.network :public_network,
        :dev => "eth1"#,
        #:mode => "bridge",
        #:type => "bridge"
      ubuntu200.vm.provider :libvirt do |libvirt|
        libvirt.memory = 384
      end
    end
  end

end
