Vagrant.configure("2") do |config|

  require '../../modules/VMs_loop.rb'
  include VMs_loop

  require '../../modules/Network_cards.rb'
  include Network_cards

  config.vm.box = "generic/ubuntu2004"

  # Ubuntu VMs for INT_CARD
  (1..N).each do |i|
    config.vm.define "ubuntu-INT-#{i}" do |ubuntu|
      ubuntu.vm.hostname = "ubuntu-INT-#{i}"
      ubuntu.vm.network "public_network", dev: INT_CARD, mode: "bridge", type: "bridge"
      ubuntu.vm.provider "libvirt" do |lv|
        lv.memory = 384
      end
    end
  end

  # Ubuntu VMs for EXT_CARD_1
  (1..N).each do |i|
    config.vm.define "ubuntu-EXT-1-#{i}" do |ubuntu|
      ubuntu.vm.hostname = "ubuntu-EXT-1-#{i}"
      ubuntu.vm.network "public_network", dev: EXT_CARD_1, mode: "bridge", type: "bridge"
      ubuntu.vm.provider "libvirt" do |lv|
        lv.memory = 384
      end
    end
  end

end