Vagrant.configure("2") do |config|

  # alpine
  config.vm.define "alpine" do |alpine|
    alpine.vm.box = "generic/alpine313"
    alpine.vm.hostname = "alpine"
    alpine.vm.provider :libvirt do |lv|
      lv.memory = 512
    end
  end

  # 20 alpine
  N = 19
  (0..N).each do |i|
    config.vm.define "alpine-#{i}" do |alpine|
      alpine.vm.box = "generic/alpine313"
      alpine.vm.hostname = "alpine-#{i}"
      #alpine.vm.network :public_network,
        #:dev => "legion"#,
        #:mode => "bridge",
        #:type => "bridge"
      alpine.vm.provider :libvirt do |lv|
        lv.memory = 128
      end
      alpine.vm.provider "virtualbox" do |vb|
        vb.memory = 128
        vb.gui = true
      end
    end  
  end

end
