Vagrant.configure("2") do |config|

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/stream8"
    centos.vm.hostname = "centos"
  end

  config.vm.define "docker" do |docker|
    docker.vm.box = "centos/stream8"
    docker.vm.hostname = "docker"
    docker.vm.provision :docker
    docker.vm.provision :docker_compose
  end

  config.vm.define "cockpit-ansible" do |cockpit|
    cockpit.vm.box = "centos/stream8"
    cockpit.vm.hostname = "cockpit"
    cockpit.vm.provision "ansible" do |ansible|
      ansible.become = true
      ansible.playbook = "../provisioning/ansible/yum/cockpit.yml"
    end
  end

  config.vm.define "cfengine" do |cfe|
    cfe.vm.box = "centos/stream8"
    cfe.vm.hostname = "cfengine"
    cfe.vm.provision "cfengine" do |cf|
      cf.am_policy_hub = true
    end
  end

end
