Vagrant.configure("2") do |config|

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/stream8"
    centos.vm.hostname = "centos"
  end

  config.vm.define "docker" do |docker|
    docker.vm.box = "centos/stream8"
    docker.vm.hostname = "docker"
    docker.vm.provision :docker
    docker.vm.provision :docker_compose
  end

end
