# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "almalinux/8"
  config.vm.provision "shell", inline: <<-SHELL
     echo a > a.txt
     grep -q a a.txt
  SHELL

end
