Vagrant.configure("2") do |config|

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "centos"
  end

  config.vm.define "docker" do |docker|
    docker.vm.box = "centos/7"
    docker.vm.hostname = "docker"
    #docker.vm.provision "shell", path: "../../../provision/shell/yum/docker.sh"
    #docker.vm.provision "shell", path: "../../../provision/shell/yum/docker-compose.sh"
    docker.vm.provision :docker
    docker.vm.provision :docker_compose
  end

  config.vm.define "cfengine" do |cfe|
    cfe.vm.box = "centos/7"
    cfe.vm.hostname = "cfengine"
    cfe.vm.provision "cfengine" do |cf|
      cf.am_policy_hub = true
    end
  end

end
