Vagrant.configure("2") do |config|

    config.vm.define "ubuntu" do |ubuntu|
      ubuntu.vm.box = "generic/ubuntu2004"
      ubuntu.vm.hostname = "ubuntu"
      ubuntu.vm.provision "chef_zero" do |chef|
        chef.cookbooks_path = "../cookbooks"
        chef.add_recipe "cockpit"
        chef.synced_folder_type = "rsync"
      end
    end

end