Vagrant.configure("2") do |config|

  # 20 alpine bridge mode to Ethernet Card
  INTERNAL = "legion"
  N = 19
  (0..N).each do |i|
    config.vm.define "alpine-#{i}" do |alpine|
      alpine.vm.box = "generic/alpine313"
      alpine.vm.hostname = "alpine-#{i}"
      alpine.vm.network :public_network,
        :dev => INTERNAL#,
        #:mode => "bridge",
        #:type => "bridge"
      alpine.vm.provider :libvirt do |lv|
        lv.memory = 128
      end
      alpine.vm.provider "virtualbox" do |vb|
        vb.memory = 128
        vb.gui = true
      end
    end  
  end

end


