Vagrant.configure("2") do |config|

  require '../VMs_loop.rb'
  include VMs_loop

  require '../Network_cards.rb'
  include Network_cards

  # alpine VMs in bridged mode to INT_CARD
  (1..N).each do |i|
    config.vm.define "alpine-INT-#{i}" do |alpine|
      alpine.vm.box = "generic/alpine313"
      alpine.vm.hostname = "alpine-#{i}"
      alpine.vm.network :public_network,
        :dev => INT_CARD#,
        #:mode => "bridge",
        #:type => "bridge"
      alpine.vm.provider :libvirt do |lv|
        lv.memory = 128
      end
      alpine.vm.provider "virtualbox" do |vb|
        vb.memory = 128
        vb.gui = true
      end
    end  
  end

end


