# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "windows10" do |win|
    win.vm.box = "StefanScherer/windows_10"
    win.vm.hostname = "windows10"
  end

end
