# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "peru/windows-10-enterprise-x64-eval"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "libvirt" do |lv|
    lv.cpus = "2"
    lv.memory = "1024"
  end
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "1024"
  end

  config.vm.define "windows" do |vm|
    vm.vm.hostname = "windows"
  end

  config.vm.define "windows-ansible" do |vm|
    vm.vm.hostname = "windows"
    vm.vm.provision "ansible" do |a|
      a.playbook = "playbook.yml"
    end
  end

end
