Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine313"

  config.vm.define "alpine" do |alpine|
    alpine.vm.hostname = "alpine"
    alpine.vm.provider :libvirt do |lv|
      lv.memory = 512
    end
  end

end
