Vagrant.configure("2") do |config|

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "centos"
  end

  config.vm.define "docker" do |docker|
    docker.vm.box = "centos/7"
    docker.vm.hostname = "docker"
    #docker.vm.provision "shell", path: "../scripts/yum/docker.sh"
    #docker.vm.provision "shell", path: "../scripts/yum/docker-compose.sh"
    docker.vm.provision :docker
    docker.vm.provision :docker_compose
  end

end
