# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "opensuse/Tumbleweed.x86_64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "opensuse" do |vm|
    vm.vm.hostname = "opensuse"
  end

end
