# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "archlinux/archlinux"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "archlinux" do |vm|
    vm.vm.hostname = "archlinux"
  end

end
