Vagrant.configure("2") do |config|

  config.vm.define "kali" do |kali|
    kali.vm.box = "kalilinux/rolling"
    kali.vm.hostname = "kali"
    kali.vm.synced_folder ".", "/vagrant", disabled: true
  end

  config.vm.define "kali-large" do |kaliL|
    kaliL.vm.box = "kalilinux/rolling"
    kaliL.vm.hostname = "kali"
    kaliL.vm.synced_folder ".", "/vagrant", disabled: true
    #kaliL.vm.provision "shell", path: "../scripts/apt/dist-upgrade.sh"
    kaliL.vm.provision "shell", path: "../scripts/apt/kali-large.sh"
  end

end
