- hosts: all
  tasks:

  - name: Install Cockpit
    yum:
      name: cockpit
      state: present

  - name: Start service Cockpit
    command: systemctl enable --now cockpit.socket

# this fails
#  - name: Start service Cockpit
#    service:
#      name: cockpit
#      state: started
