# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_BOX = ENV["VM_BOX"] || "peru/windows-server-2016-standard-x64-eval"
VM_RAM = ENV["VM_RAM"] || "1024"
VM_CPU = ENV["VM_CPU"] || "2"

Vagrant.configure("2") do |config|

  config.vm.box = VM_BOX
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "libvirt" do |lv|
    lv.memory = VM_RAM
    lv.cpus = VM_CPU
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = VM_RAM
    vb.cpus = VM_CPU
  end

  config.vm.define "windows" do |vm|
    vm.vm.hostname = "windows"
  end

end
